"""Read-only actual MAT state_dict checkpoint and snapshot analysis smoke."""
import json
import tempfile
import unittest
from pathlib import Path

import numpy as np
import torch

from mat.algorithms.mat.algorithm.ma_transformer import MultiAgentTransformer
from research.dependency_decoder.checkpoint_diagnostic import (
    run_diagnostic, main, _load_snapshot,
)


class TestCheckpointDiagnostic(unittest.TestCase):

    def create_fixture(self, tmp):
        torch.manual_seed(9821)
        model = MultiAgentTransformer(
            state_dim=37, obs_dim=7, action_dim=4, n_agent=3,
            n_block=1, n_embd=8, n_head=1, encode_state=False,
            action_type="Discrete")
        checkpoint = tmp / "transformer_0.pt"
        torch.save(model.state_dict(), checkpoint)
        obs = np.random.default_rng(9822).normal(size=(2, 3, 7)).astype(np.float32)
        legal = np.ones((2, 3, 4), dtype=np.float32)
        legal[0, 0, 2] = 0
        order = np.array([[2, 0, 1], [1, 2, 0]], dtype=np.int64)
        snapshot = tmp / "MAT_diag_snapshot.npz"
        np.savez_compressed(snapshot, obs=obs, available_actions=legal,
                            agent_order=order)
        return checkpoint, snapshot

    def test_real_model_checkpoint_sampling_and_kl_metrics(self):
        with tempfile.TemporaryDirectory() as dirname:
            checkpoint, snapshot = self.create_fixture(Path(dirname))
            data = run_diagnostic(
                checkpoint, snapshot, n_block=1, n_embd=8, n_head=1,
                num_histories=5, max_context_batch=2,
                max_counterfactual_batch=4, seed=9823)
            self.assertEqual(data["snapshot_contexts"], 2)
            # Joint policy entropy is estimated from the ALREADY
            # sampled complete-action log probabilities, no re-decoding.
            self.assertAlmostEqual(
                data["joint_action_entropy_mc_mean_nats"],
                -data["sampled_joint_logp_mean"], places=5)
            self.assertEqual(
                len(data["joint_action_entropy_mc_nats_by_context"]), 2)
            self.assertEqual(
                len(data["joint_action_entropy_mc_se_nats_by_context"]), 2)
            self.assertTrue(all(v >= 0 for v in
                                data["joint_action_entropy_mc_nats_by_context"]))
            self.assertTrue(all(v >= 0 for v in
                                data["joint_action_entropy_mc_se_nats_by_context"]))
            self.assertTrue(all(v > 0 for v in
                                data["legal_action_entropy_ceiling_nats_by_context"]))
            self.assertEqual(data["sampled_histories"], 5)
            self.assertEqual(data["n_agents"], 3)
            self.assertLess(data["max_sampling_likelihood_error"], 2e-5)
            self.assertGreater(data["observable_directed_pairs"], 0)
            self.assertEqual(data["bidirectionally_observable_pairs"], 0)
            self.assertLessEqual(data["observable_directed_pairs"], 6)
            self.assertIsNotNone(data["mean_observable_kl"])
            self.assertIsNotNone(data["mean_observable_tv"])
            self.assertGreaterEqual(data["mean_observable_tv"], 0)
            self.assertLessEqual(data["max_observable_tv"], 1)
            self.assertGreaterEqual(data["max_pinsker_excess"], 0)
            self.assertLess(data["max_pinsker_excess"], 1e-8)
            self.assertEqual(len(data["mean_tv_by_context"]), 2)
            self.assertGreaterEqual(data["min_observed_ess"], 1)
            self.assertTrue(data["diagnostic_only"])
            self.assertFalse(data["trained_smac_performance_claim"])

    def test_cli_json_is_finite_and_does_not_modify_checkpoint(self):
        with tempfile.TemporaryDirectory() as dirname:
            path = Path(dirname)
            checkpoint, snapshot = self.create_fixture(path)
            before = checkpoint.read_bytes()
            output = path / "analysis.json"
            report = main([
                "--checkpoint", str(checkpoint),
                "--snapshot", str(snapshot),
                "--n-block", "1", "--n-embd", "8", "--n-head", "1",
                "--num-histories", "3", "--max-context-batch", "2",
                "--max-counterfactual-batch", "4",
                "--output", str(output),
            ])
            self.assertEqual(checkpoint.read_bytes(), before)
            self.assertEqual(report, json.loads(output.read_text()))
            self.assertIn("unobservable", report["warning"].replace(
                "Only predecessor-to-successor", "unobservable predecessor-to-successor"))
            # No training/SC2 data is generated by this CLI.

    def test_entropy_one_history_has_null_standard_error_not_nan(self):
        with tempfile.TemporaryDirectory() as dirname:
            checkpoint, snapshot = self.create_fixture(Path(dirname))
            data = run_diagnostic(
                checkpoint, snapshot, n_block=1, n_embd=8, n_head=1,
                num_histories=1, max_context_batch=2,
                max_counterfactual_batch=4, seed=9824)
            self.assertEqual(
                data["joint_action_entropy_mc_se_nats_by_context"],
                [None, None])
            self.assertAlmostEqual(
                data["joint_action_entropy_mc_mean_nats"],
                -data["sampled_joint_logp_mean"], places=5)

    def test_invalid_snapshot_or_checkpoint_fails_closed(self):
        with tempfile.TemporaryDirectory() as dirname:
            path = Path(dirname)
            checkpoint, snapshot = self.create_fixture(path)
            with self.assertRaises((RuntimeError, ValueError)):
                run_diagnostic(checkpoint, snapshot, 2, 8, 1,
                               num_histories=2)
            with np.load(snapshot, allow_pickle=False) as source:
                obs = source["obs"]
                legal = source["available_actions"]
            malformed = path / "broken.npz"
            np.savez_compressed(
                malformed, obs=obs, available_actions=legal,
                agent_order=np.array([[0, 0, 2], [1, 2, 0]], dtype=np.int64))
            with self.assertRaises(ValueError):
                _load_snapshot(malformed)
            illegal = path / "illegal.npz"
            legal[:, 1] = 0
            np.savez_compressed(illegal, obs=obs, available_actions=legal,
                agent_order=np.array([[0, 1, 2], [0, 1, 2]], dtype=np.int64))
            with self.assertRaises(ValueError):
                _load_snapshot(illegal)


if __name__ == "__main__":
    unittest.main()
